export const FLOOR = [
    "qttttttttttttt||tttttttttttttp",
    "                              ",
    "                              ",
    "                              ",
    "                              ",
    "                              ",
    "                              ",
    "                              ",
    "                              ",
    "                              ",
    "                              ",
    "                              ",
    "                              ",
    "                              ",
];

export const LEVEL0 = [
    "         ewwwwwwwwwwwo        ",
    "         s           d        ",
    "     ewwwh           d        ",
    "     s               nwwo     ",
    "     s                  d     ",
    "     s                  d     ",
    "     ,aaaaf             d     ",
    "          s             nwwwwo",
    "          ,af                d",
    "            s                d",
    "            s                d",
    "            s        gaaaaaaa.",
    "            s        d        ",
    "            ,aaaaaaaa.        ",
];

export const LEVEL1 = [
    "iiiqttttpiiqttjkttpiiqttttriii",
    "iqtt    ttpq      pqtt    ttpi",
    "lt        pq      pq        tr",
    "l         pq      pq         r",
    "l         tt      tt         r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l         yu      yu         r",
    "l         rl      rl         r",
    "zbu       rl      rl       ybm",
    "iizu    ybmzbu  ybmzbu    ymii",
    "iiizbbbbmiiiizbbmiiiizbbbbmiii",
];

export const LEVEL2 = [
    "iiiqttttttttttjkttttttttttriii",
    "iqtt                      ttpi",
    "lt                          tr",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "zbu                        ybm",
    "iizu                      ymii",
    "iiizbbbbbbbbbbbbbbbbbbbbbbmiii",
];

export const LEVEL3 = [
    "iiiqttttpiiqttjkttpiiqttttriii",
    "iqtt    ttpq      pqtt    ttpi",
    "lt        pq      pq        tr",
    "l         pq      pq         r",
    "l         tt      tt         r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l         yu      yu         r",
    "l         rl      rl         r",
    "zbu       rl      rl       ybm",
    "iizu    ybmzbu  ybmzbu    ymii",
    "iiizbbbbmiiiizbbmiiiizbbbbmiii",
];

export const LEVEL4 = [
    "iiiqttttttttttjkttttttttttriii",
    "iqtt                      ttpi",
    "lt                          tr",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "zbu                        ybm",
    "iizu                      ymii",
    "iiizbbbbbbbbbbbbbbbbbbbbbbmiii",
];

export const LEVEL5 = [
    "iiiqttttpiiqttjkttpiiqttttriii",
    "iqtt    ttpq      pqtt    ttpi",
    "lt        pq      pq        tr",
    "l         pq      pq         r",
    "l         tt      tt         r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l         yu      yu         r",
    "l         rl      rl         r",
    "zbu       rl      rl       ybm",
    "iizu    ybmzbu  ybmzbu    ymii",
    "iiizbbbbmiiiizbbmiiiizbbbbmiii",
];

export const LEVEL6 = [
    "iiiqttttttttttjkttttttttttriii",
    "iqtt                      ttpi",
    "lt                          tr",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "zbu                        ybm",
    "iizu                      ymii",
    "iiizbbbbbbbbbbbbbbbbbbbbbbmiii",
];

export const LEVEL_WIN = [
    "iiiqttttttttttjkttttttttttriii",
    "iqtt                      ttpi",
    "lt                          tr",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "zbu                        ybm",
    "iizu                      ymii",
    "iiizbbbbbbbbbbbbbbbbbbbbbbmiii",
];

