export const FLOOR = [
    "qttttttttttttt||tttttttttttttp",
    "                              ",
    "                              ",
    "                              ",
    "                              ",
    "                              ",
    "                              ",
    "                              ",
    "                              ",
    "                              ",
    "                              ",
    "                              ",
    "                              ",
    "                              ",
];

export const LEVEL0 = [
    "         ewwwwwwwwwwwo        ",
    "         s           d        ",
    "     ewwwh           d        ",
    "     s               nwwo     ",
    "     s                  d     ",
    "     s                  d     ",
    "     ,aaaaf             d     ",
    "          s             nwwwwo",
    "          ,af                d",
    "            s                d",
    "            s                d",
    "            s        gaaaaaaa.",
    "            s        d        ",
    "            ,aaaaaaaa.        ",
];

export const LEVEL1 = [
    "qtttttttttttttjktttttttttttttp",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "zbbbbbbbbbbbbbbbbbbbbbbbbbbbbm",
];

export const LEVEL2 = [
    "qtttttttttttttjktttttttttttttp",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "zbbbbbbbbbbbbbbbbbbbbbbbbbbbbm",
];

export const LEVEL3 = [
    "qtttttttttttttjktttttttttttttp",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "zbbbbbbbbbbbbbbbbbbbbbbbbbbbbm",
];

export const LEVEL4 = [
    "qtttttttttttttjktttttttttttttp",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "zbbbbbbbbbbbbbbbbbbbbbbbbbbbbm",
];

export const LEVEL5 = [
    "qtttttttttttttjktttttttttttttp",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "zbbbbbbbbbbbbbbbbbbbbbbbbbbbbm",
];

export const LEVEL6 = [
    "qtttttttttttttjktttttttttttttp",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "zbbbbbbbbbbbbbbbbbbbbbbbbbbbbm",
];

export const LEVEL_WIN = [
    "qtttttttttttttjktttttttttttttp",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "zbbbbbbbbbbbbbbbbbbbbbbbbbbbbm",
];

