export const FLOOR = [
    "qttttttttttttt||tttttttttttttp",
    "                              ",
    "                              ",
    "                              ",
    "                              ",
    "                              ",
    "                              ",
    "                              ",
    "                              ",
    "                              ",
    "                              ",
    "                              ",
    "                              ",
    "                              ",
];

export const LEVEL0 = [
    "ewwwwwwwwwwwwwjkwwwwwwwwwwwwwo",
    "s                            d",
    "s                            d",
    "s                            d",
    "s                            d",
    "s                            d",
    "s                            d",
    "s                            d",
    "s                            d",
    "s                            d",
    "s                            d",
    "s                            d",
    "s                            d",
    ",aaaaaaaaaaaaaaaaaaaaaaaaaaaa.",
];

export const LEVEL1 = [
    "qtttttttttttttjktttttttttttttp",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "zbbbbbbbbbbbbbbbbbbbbbbbbbbbbm",
];

export const LEVEL2 = [
    "qtttttttttttttjktttttttttttttp",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "zbbbbbbbbbbbbbbbbbbbbbbbbbbbbm",
];

export const LEVEL3 = [
    "qtttttttttttttjktttttttttttttp",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "zbbbbbbbbbbbbbbbbbbbbbbbbbbbbm",
];

export const LEVEL4 = [
    "qtttttttttttttjktttttttttttttp",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "zbbbbbbbbbbbbbbbbbbbbbbbbbbbbm",
];

export const LEVEL5 = [
    "qtttttttttttttjktttttttttttttp",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "zbbbbbbbbbbbbbbbbbbbbbbbbbbbbm",
];

export const LEVEL6 = [
    "qtttttttttttttjktttttttttttttp",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "zbbbbbbbbbbbbbbbbbbbbbbbbbbbbm",
];

export const LEVEL_WIN = [
    "qtttttttttttttjktttttttttttttp",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "l                            r",
    "zbbbbbbbbbbbbbbbbbbbbbbbbbbbbm",
];

